<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * childrenGoodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class childrenGoodsRepository extends EntityRepository
{
}
